name: Guan's Research Lab
description: Guan's Research Lab at Kent State University
url: http://guans.cs.kent.edu/

markdown: kramdown
permalink: /:categories/:title/
future: true

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "deploy.sh"
  - "ghp_deploy.sh"
